### ISSUE TITLE
Undefined Variable error message on Pool task stats page (https://grc.arikado.ru/tasks.php)

### ISSUE THREAD

**Issue by barton2526** [sau412/arikado_gridcoin_pool#5]
On https://grc.arikado.ru/tasks.php I see the following error message at the top of the page:

`Notice: Undefined variable: page in /var/www/u0403486/data/www/gridcoinpool.ru/tasks.php on line 38`

Screenshot:

![error](https://user-images.githubusercontent.com/20938755/44170702-1f016300-a0a6-11e8-9ec9-e923dcc7eece.PNG)

**Comment by sau412** [comment]
Fixed.
https://github.com/sau412/arikado_gridcoin_pool/commit/381db4f97acd0c9284a5fc8715cd02de3acec8e9

Need your address to send reward

**Comment by barton2526** [comment]
No payment is necessary.  If you want, you can donate my bounty to your pool crunchers or a faucet of your choosing :)
