### ISSUE TITLE
Work on Implementing a Mobile Version of the Site

### ISSUE THREAD

**Issue by RoboticMind** [sau412/arikado_gridcoin_pool#6]
The title says it all

**Comment by sau412** [comment]
Done!
https://github.com/sau412/arikado_gridcoin_pool/commit/16414da902153294e7cc753b97c0e9f71b0dc765
https://github.com/sau412/arikado_gridcoin_pool/commit/538d2ce311b4a01ffdf867a9f960528428593d1b
https://github.com/sau412/arikado_gridcoin_pool/commit/de79af63b9d187592be329581a19d012ce8a98e0
